version: '3.8'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./data/phdev:/var/lib/postgresql/data
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  db:
    driver: local
