version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./data/phdev:/var/lib/postgresql/data
  web:
    image: ejmercado/wemeowt:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '3000:3000'
    depends_on:
      - db
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest:latest
    ports:
      - '80:3000'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGRST_DB_URI=${PGRST_DB_URI}
      - PGRST_DB_SCHEMAS=public
      - PGRST_DB_ANON_ROLE=${POSTGRES_ANON_ROLE}
    depends_on:
      - db

volumes:
  db:
    driver: local
