version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phdev
    ports:
      - '5432:5432'
    volumes: 
      - ./data/phdev:/var/lib/postgresql/data
volumes:
  db:
    driver: local