name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cleanup Disk
      run: |
        docker system prune -af
        sudo rm -rf /usr/local/lib/android/sdk

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ejmercado/wemeowt:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.DROPLET_PRIVATE_KEY }}
        port: ${{ secrets.DROPLET_PORT }}
        script: |
          cd /root/projects/ph-dev
          git pull
          docker-compose pull web
          docker-compose up -d --build web
